name: test

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup Fortran
      uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy scipy
        sudo apt update

    - name: build python
      run: python -m pip install . -v

    - name: test python
      working-directory: ${{github.workspace}}/test
      run: python test.py

